trigger: none # Need manual trigger

parameters:
- name: releaseType
  displayName: Release Type
  type: string
  default: Test
  values:
  - Test
  - Production
  
variables:
  ${{ if eq(variables.releaseType, 'Test')}}:
    twineConnection: testpypi
  ${{ if eq(parameters.releaseType, 'Production')}}:
    twineConnection: pypi

strategy:
  matrix:
    linux_x64_py3.6:
      imageName: 'ubuntu-18.04'
      python.version: '3.6'

pool:
    vmImage: '$(imageName)'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python $(python.version)'

- bash: |
    pip install --upgrade pip 
    pip install setuptools wheel
    pip install -r requirements.txt 
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Install dependencies'

- bash: |
    python setup.py bdist_wheel --dist-dir dist
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Building wheel package'

- bash: |
    pip install twine
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Install twine' 

- task: TwineAuthenticate@1
  inputs:
    pythonUploadServiceConnection: ${{variables.twineConnection}}
  displayName: 'Twine Authentication'

- bash: |
    twine upload --verbose -r genalog --config-file $(PYPIRC_PATH) dist/*
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Uploading wheel package to ${{parameters.releaseType}} PyPI ${{variables.twineConnection}}'