# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# ---------------------------------------------------------

# Assume a python version is enabled with "UsePythonVersion@0" task
steps:
- bash: |
    python -m pip install --upgrade pip setuptools wheel
    python -m pip install -r requirements-dev.txt
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Install dependencies'
