# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# ---------------------------------------------------------

parameters:
- name: pyVersions
  type: object
  default: ['3.6', '3.7', '3.8']
- name: testTypes
  type: object
  default: ['fast', 'slow']
- name: imageOSs
  type: object
  default: ['ubuntu-latest']

jobs:
  - ${{ each imageOS in parameters.imageOSs }}:
    - ${{ each pyVersion in parameters.pyVersions }}:
      - job:
        displayName: ${{imageOS}} py${{pyVersion}}
        pool:
          vmImage: ${{imageOS}}
        steps:

        - task: UsePythonVersion@0
          inputs:
            versionSpec: ${{pyVersion}}
            addToPath: true
            architecture: 'x64'
          displayName: 'Use Python ${{pyVersion}}'

        - template: install-dependencies.yml

        - ${{ each testType in parameters.testTypes }}:
          - template: base/run-tests.yml
            parameters:
              testType: ${{testType}}
          - template: base/publish-test-results.yml
            parameters:
              pyVersion: ${{pyVersion}}

        - bash: |
            mv .coverage .coverage_$(System.StageName)_${{imageOS}}_${{pyVersion}}
            ls .coverage*
          workingDirectory: $(Build.SourcesDirectory)
          displayName: 'Rename coverage report'
        # Cache the coverage report
        - publish: $(Build.SourcesDirectory)/.coverage_$(System.StageName)_${{imageOS}}_${{pyVersion}}
          artifact: cov_report_$(System.StageName)_${{imageOS}}_${{pyVersion}}